// ============================================
// Chat Export Utility
// ============================================
// Exports chat as formatted TXT or JSON
// Restored from original chat.js exportChat
// ============================================

// ==========================================
// EXPORT AS FORMATTED TEXT
// ==========================================
export function exportChatAsText(messages, sessionId, context) {
  if (!messages || messages.length === 0) {
    alert('No messages to export!');
    return;
  }

  const conversationDuration = context.conversationDuration || 0;
  const topicsDiscussed = context.topicsDiscussed || [];

  // Header
  const header = [
    '╔══════════════════════════════════════════════════════════════╗',
    '║           PAGETURNER BOOKS - CHAT TRANSCRIPT               ║',
    '╚══════════════════════════════════════════════════════════════╝',
    '',
    `📅 Exported: ${new Date().toLocaleString()}`,
    `🔑 Session ID: ${sessionId}`,
    `💬 Total Messages: ${messages.length}`,
    `⏱️ Session Duration: ${conversationDuration} minutes`,
    `🎯 Topics Discussed: ${topicsDiscussed.join(', ') || 'N/A'}`,
    '',
    '═'.repeat(65),
    ''
  ].join('\n');

  // Messages
  const chatContent = messages.map((msg) => {
    const role = msg.role === 'user' ? '👤 YOU' : '🤖 PAGETURNER BOT';
    const time = msg.timestamp || 'N/A';
    const intent = msg.intent ? ` [${msg.intent}]` : '';

    const cleanContent = msg.content
      .replace(/\*\*/g, '')
      .replace(/\*/g, '')
      .replace(/#{1,6}\s/g, '');

    return [
      `┌─────────────────────────────────────────────────────────────┐`,
      `│ ${role} - ${time}${intent}`,
      `├─────────────────────────────────────────────────────────────┤`,
      `│`,
      cleanContent.split('\n').map(line => `│ ${line}`).join('\n'),
      `│`,
      `└─────────────────────────────────────────────────────────────┘`,
      ''
    ].join('\n');
  }).join('\n');

  // Footer
  const footer = [
    '',
    '═'.repeat(65),
    '',
    '📊 SESSION SUMMARY',
    '─'.repeat(30),
    `• Questions Asked: ${context.questionsAsked || 0}`,
    `• Favorite Genre: ${context.preferences?.favoriteGenre || 'Not specified'}`,
    `• Last Book Viewed: ${context.lastBookMentioned || 'N/A'}`,
    `• Last Order Checked: ${context.lastOrderChecked || 'N/A'}`,
    '',
    '═'.repeat(65),
    '',
    'Thank you for chatting with PageTurner Books!',
    '📚 Visit us again soon!',
    '',
    `Generated by PageTurner AI Chat Assistant © ${new Date().getFullYear()}`
  ].join('\n');

  const fullExport = header + chatContent + footer;

  downloadFile(
    fullExport,
    `PageTurner-Chat-${sessionId.slice(-8)}-${new Date().toISOString().slice(0, 10)}.txt`,
    'text/plain;charset=utf-8'
  );

  console.log('📥 Chat exported as TXT successfully!');
}

// ==========================================
// EXPORT AS JSON
// ==========================================
export function exportChatAsJSON(messages, sessionId, context) {
  if (!messages || messages.length === 0) {
    alert('No messages to export!');
    return;
  }

  const exportData = {
    sessionId,
    exportedAt: new Date().toISOString(),
    messageCount: messages.length,
    conversationContext: context,
    messages
  };

  downloadFile(
    JSON.stringify(exportData, null, 2),
    `PageTurner-Chat-${sessionId.slice(-8)}.json`,
    'application/json'
  );

  console.log('📥 Chat exported as JSON successfully!');
}

// ==========================================
// DOWNLOAD FILE HELPER
// ==========================================
function downloadFile(content, filename, contentType) {
  const blob = new Blob([content], { type: contentType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// ==========================================
// ADMIN DATA EXPORT
// ==========================================
export function exportAdminData(books, orders, faqs, chatLogs, analytics) {
  const exportObj = {
    exportedAt: new Date().toISOString(),
    books,
    orders,
    faqs,
    chatLogs,
    analytics
  };

  downloadFile(
    JSON.stringify(exportObj, null, 2),
    `pageturner-admin-export-${new Date().toISOString().slice(0, 10)}.json`,
    'application/json'
  );

  console.log('📥 Admin data exported');
}